[phases.setup]
nixPkgs = ['bun', 'nodejs_22']
nixpkgsArchive = '12bd230118a1901a4a5d393f9f56b6ad7e571d01'
aptPkgs = ["gcc", "g++", "make", "python3"]

[phases.install]
cmds = ['bun install --frozen-lockfile', 'npm rebuild better-sqlite3']

[phases.runtime]
nixLibs = ['gcc13.cc.lib']
