[phases.setup]
nixPkgs = ['bun', 'nodejs_22']
nixpkgsArchive = 'e57b3b16ad8758fd681511a078f35c416a8cc939'
aptPkgs = ["gcc", "g++", "make", "python3"]

[phases.install]
cmds = ['bun install --frozen-lockfile', 'npm rebuild better-sqlite3']

[phases.runtime]
nixLibs = ['gcc.cc.lib']
nixpkgsArchive = 'e57b3b16ad8758fd681511a078f35c416a8cc939'
